---
- hosts: all
  become: true
  tasks:

  - name: Install Latest Python3 and Pip3 in Ubuntu
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - python3
      - python3-pip
    when: ansible_distribution == 'Ubuntu'

  - name: Install Latest Python3 and Pip3 in CentOS
    dnf:
      name: "{{ item }}"
      state: latest
    with_items:
      - python3
      - python3-pip
    when: ansible_distribution == 'CentOS'

  - name: Use Pip3 as Default Pip in Ubuntu
    command: "ln -sf /usr/bin/pip3 /usr/bin/pip"
    when: ansible_distribution == 'Ubuntu'

  - name: Use Pip3 as Default Pip in CentOS
    command: "ln -sf /usr/bin/pip3 /usr/bin/pip"
    when: ansible_distribution == 'CentOS'

  - name: Use Python3 as Default Python in Ubuntu
    command: "ln -sf /usr/bin/python3 /usr/bin/python"
    when: ansible_distribution == 'Ubuntu'

  - name: Use Python3 as Default Python in CentOS
    command: "ln -sf /usr/bin/python3 /usr/bin/python"
    when: ansible_distribution == 'CentOS'

  - name: Install Java OpenJDK in Ubuntu
    apt:
      name: openjdk-17-jdk
      state: latest
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

  - name: Install Java OpenJDK in CentOS
    dnf:
      name: openjdk-11-jdk
      state: latest
      update_cache: yes
    when: ansible_distribution == 'CentOS'

  - name: Create MOTD
    template:
      src: /home/marl/Potal_PrelimExam/motd.j2
      dest: /etc/motd
    vars:
      motd_text: "{{ motd_variable | default('Ansible Managed node by marl') }}"

  - name: Create User
    user:
      name: "{{ new_user }}"
      state: present
